In [4]:
import numpy as np

In [21]:
a = [30,40,20,40,30] # List
arr = np.array(a) # List converts into Numpy Array
print(arr)
print(arr.shape) # Gives number of columns as 5
print(len(arr)) # length of arr how many elements in arr
print(np.size(arr)) # Give all elemets available in array
print(type(arr)) # Give type of array which is n dimensional
print(arr.dtype) # print type of data in array
print(arr.astype(float)) # convert int data into float and prints
print(arr.astype(str)) # convert int data into float and prints

[30 40 20 40 30]
(5,)
5
5
<class 'numpy.ndarray'>
int64
[30. 40. 20. 40. 30.]
['30' '40' '20' '40' '30']


In [20]:
a = [[30,40],[40,30],[50,60]] # List
arr = np.array(a) # List converts into Numpy Array
print(arr)
print(arr.shape) # Gives number of rows and columns
print(len(arr)) # length of arr how many array present
print(np.size(arr)) # Give all elemets available in array
print(type(arr)) # Give type of array which is n dimensional
print(arr.dtype) # print type of data in array
print(arr.astype(float)) # convert int data into float and prints
print(arr.astype(str)) # convert int data into string and prints (In numpy array if we have one value float then full array in convert in float, if we want we can also change into int)

[[30 40]
 [40 30]
 [50 60]]
(3, 2)
3
6
<class 'numpy.ndarray'>
int64
[[30. 40.]
 [40. 30.]
 [50. 60.]]
[['30' '40']
 ['40' '30']
 ['50' '60']]
