In [2]:
import numpy as np

a = np.array([20,40,60,70])

print(np.sum(a))

190


In [6]:
print(np.max(a))

70


In [7]:
print(np.min(a))

20


In [13]:
print(np.size(a)) # Size of array 4 elements

4


In [10]:
print(np.mean(a))

47.5


In [12]:
print(np.cumsum(a)) # Cummulative Sum

[ 20  60 120 190]


In [14]:
print(np.cumprod(a)) # Cummulative Product of a

[     20     800   48000 3360000]


In [3]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)
print(price, "\n" ,quantity)

print(np.sum(price))

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]
1029


In [4]:
print(np.cumprod([price,quantity], axis = 0)) # It prints like 100*10 and 150*50

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]


In [8]:
total = np.cumprod([price,quantity], axis = 0)
print(total)
print(total[1])

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]
[1000 7500 5970 8000 7500 1300]


In [9]:
print(total[1].sum())

31270
